[package]
name = "free-icons"
version = "0.1.0"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/accept-header"
repository = "https://github.com/tyrchen/accept-header"
homepage = "https://github.com/tyrchen/accept-header"
description = """
Use free svg icons in your html projects
"""
readme = "README.md"
categories = ["web-programming"]
keywords = ["icons", "svg"]
include = [
    "Cargo.toml",
    "build.rs",
    "src/lib.rs",
    "src/gen/*.rs",
    "templates/*.j2",
]


[features]
default = ["bootstrap", "feather", "font-awesome", "heroicons", "ionicons", "octicons"]
bootstrap = []
feather = []
font-awesome = []
heroicons = []
ionicons = []
octicons = []

[dependencies]
phf = { version = "0.11.1", features = ["macros"] }

[build-dependencies]
anyhow = "1.0.66"
convert_case = "0.6.0"
minify-html = "0.10.3"
tera = "1.17.1"

[dev-dependencies]
minify-html = "0.10.3"
