[package]
name = "free-icons"
version = "0.1.0"
edition = "2021"


[features]
default = ["bootstrap", "feather", "font-awesome", "heroicons", "ionicons", "octicons"]
bootstrap = []
feather = []
font-awesome = []
heroicons = []
ionicons = []
octicons = []

[dependencies]
phf = { version = "0.11.1", features = ["macros"] }

[build-dependencies]
anyhow = "1.0.66"
convert_case = "0.6.0"
minify-html = "0.10.3"
tera = "1.17.1"

[dev-dependencies]
minify-html = "0.10.3"
